SYSTEM     = x86-64_osx
LIBFORMAT  = static_pic

#------------------------------------------------------------
#
# When you adapt this makefile to compile your CPLEX programs
# please copy this makefile and set CPLEXDIR and CONCERTDIR to
# the directories where CPLEX and CONCERT are installed.
#
#------------------------------------------------------------

CPLEXDIR      = /Applications/IBM/ILOG/CPLEX_Studio_Community1262/cplex
CONCERTDIR    = /Applications/IBM/ILOG/CPLEX_Studio_Community1262/concert

# ---------------------------------------------------------------------
# Compiler selection 
# ---------------------------------------------------------------------

CCC = clang++ -O0
CC  = clang -O0

# ---------------------------------------------------------------------
# Compiler options 
# ---------------------------------------------------------------------

CCOPT = -m64 -O -fPIC -fexceptions -DNDEBUG -DIL_STD -stdlib=libstdc++
COPT  = -m64 -fPIC

# ---------------------------------------------------------------------
# Link options and libraries
# ---------------------------------------------------------------------

CPLEXLIBDIR   = $(CPLEXDIR)/lib/$(SYSTEM)/$(LIBFORMAT)
CONCERTLIBDIR = $(CONCERTDIR)/lib/$(SYSTEM)/$(LIBFORMAT)

CCLNDIRS  = -L$(CPLEXLIBDIR) -L$(CONCERTLIBDIR)
CCLNFLAGS = -lconcert -lilocplex -lcplex -m64 -lm -lpthread -framework CoreFoundation -framework IOKit -stdlib=libstdc++ -llapack -lcblas -lblas

CONCERTINCDIR = $(CONCERTDIR)/include
CPLEXINCDIR   = $(CPLEXDIR)/include

EXSRCCPP      = src
BINDIR_CPP = build

SRC_CPP = $(wildcard $(EXSRCCPP)/*.cpp)

CPP_EX = $(SRC_CPP:$(EXSRCCPP)/%.cpp=$(BINDIR_CPP)/%)

CCFLAGS = $(CCOPT) -I$(CPLEXINCDIR) -I$(CONCERTINCDIR) 

#------------------------------------------------------------
#  make all      : to compile the examples. 
#  make execute  : to compile and execute the examples.
#------------------------------------------------------------

all:
	make all_cpp

all_cpp: $(CPP_EX)

$(BINDIR_CPP)/% : $(BINDIR_CPP)/%.o
	$(CCC) $(CCFLAGS) $(CCLNDIRS) $< -o $@ $(CCLNFLAGS)

$(BINDIR_CPP)/%.o : $(EXSRCCPP)/%.cpp
	$(CCC) -c $(CCFLAGS) $< -o $@

clean :
	/bin/rm -rf *.o *~ *.class
	/bin/rm -rf $(CPP_EX) 
	/bin/rm -rf *.mps *.ord *.sos *.lp *.sav *.net *.msg *.log *.clp
